export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['Italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Burger Deluxe',
      cookTime: '15-25',
      price: 8,
      favorite: true,
      origins: ['USA'],
      stars: 4.8,
      imageUrl: 'food-2.jpg',
      tags: ['FastFood', 'Burger', 'Dinner'],
    },
    {
      id: '3',
      name: 'Pasta Carbonara',
      cookTime: '20-30',
      price: 12,
      favorite: false,
      origins: ['Italy'],
      stars: 4.7,
      imageUrl: 'food-3.jpg',
      tags: ['Italian', 'Pasta', 'Dinner'],
    },
    {
      id: '4',
      name: 'Sushi Platter',
      cookTime: '25-35',
      price: 15,
      favorite: true,
      origins: ['Japan'],
      stars: 4.9,
      imageUrl: 'food-4.jpg',
      tags: ['Japanese', 'Sushi', 'Dinner'],
    },
    {
      id: '5',
      name: 'Chicken Shawarma',
      cookTime: '15-25',
      price: 10,
      favorite: false,
      origins: ['Middle East'],
      stars: 4.4,
      imageUrl: 'food-5.jpg',
      tags: ['MiddleEastern', 'Chicken', 'Lunch'],
    },
    {
      id: '6',
      name: 'Vegetarian Curry',
      cookTime: '20-30',
      price: 12,
      favorite: true,
      origins: ['India'],
      stars: 4.6,
      imageUrl: 'food-6.jpg',
      tags: ['Indian', 'Vegetarian', 'Dinner'],
    },
  ];
  export const sample_tags = [
    {name:'All', count:6},
    {name:'FastFood', count:2},
    {name:'Pizza', count:1},
    {name:'Lunch', count:2},
    {name:'SlowFood', count:0},
    {name:'Hamburger', count:0},
    {name:'Fry', count:0},
    {name:'Soup', count:0},
  ];