export const sample_foods = [
  {
    id: '1',
    name: 'Extra Slice Pizza',
    price: 200,
    cookTime: '30M',
    favorite: true,
    origins: ['Asansol'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['Swiggy', 'Food'],
  },
  {
    id: '2',
    name: 'Car Insurance',
    cookTime: '10D',
    price: 1000,
    favorite: false,
    origins: ['Kolkata'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Insurance', 'Cars'],
  },
  {
    id: '3',
    name: 'Extra Slice Pizza',
    price: 200,
    cookTime: '30M',
    favorite: true,
    origins: ['Asansol'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['Swiggy', 'Food'],
  },
  {
    id: '3',
    name: 'Car Insurance',
    cookTime: '10D',
    price: 1000,
    favorite: false,
    origins: ['Kolkata'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Insurance', 'Cars'],
  },
  {
    id: '4',
    name: 'Extra Slice Pizza',
    price: 200,
    cookTime: '30M',
    favorite: true,
    origins: ['Asansol'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['Swiggy', 'Food'],
  },
  {
    id: '5',
    name: 'Car Insurance',
    cookTime: '10D',
    price: 1000,
    favorite: false,
    origins: ['Kolkata'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Insurance', 'Cars'],
  },
  {
    id: '6',
    name: 'Extra Slice Pizza',
    price: 200,
    cookTime: '30M',
    favorite: true,
    origins: ['Asansol'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['Swiggy', 'Food'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];